config/routes.rb
Swpuart::Application.routes.draw do

  resources :rules

  resources :sorders
  resources :line_items
  resources :carts
  resources :eorders
  resources :videos

  mount Ckeditor::Engine => '/ckeditor'

  mount Rich::Engine => '/rich', :as => 'rich'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => 'static_pages#home'
  resources :sites do
    collection do
    get 'siteorder'
    end
  end

  resources :equipment do
    collection do
      get 'list'
    end
  end

  resources :notices

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :line_items,:dependent => :destroy
end

app/models/eorder.rb
class Eorder < ActiveRecord::Base
  attr_accessible :ename,:eapplicant, :eartopinion, :ekeeper, :ereturntime, :esituation, :etel, :eusereason, :eusetime,:equipment_id
  validates :ename, :presence => true
  validates :eapplicant, :presence => true
  validates :etel, :presence => true
  validates :eusetime, :presence => true
  validates :eusereason, :presence => true

  #has_many :line_items
  #before_destroy :ensure_not_referenced_by_any_line_item

  belongs_to :equipment


  private
  def ensure_not_referenced_by_any_line_item
  	if line_items.empty?
  		return true
  	else
  		errors.add(:base,'11111')
  		return false
  	end
  end
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  attr_accessible :elist, :ename, :eprice, :eremain, :etype,:epicture,:epicture_cache,:remove_epicture
 


  mount_uploader :epicture, AvatarUploader

  # has_many :eorders, :dependent => :destroy

  validates :ename, :presence => true
  validates :eremain, :presence => true




end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :eorder_id
  belongs_to :eorder
  belongs_to :cart
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  attr_accessible :ncontent, :nfilenumber, :ntitle
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  attr_accessible :rcontent, :rpublisher, :rtitle
end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :sdescribe, :sname, :sstate,:spicture
  mount_uploader :spicture, SpictureUploader
end

app/models/sorder.rb
class Sorder < ActiveRecord::Base
  attr_accessible :sapplicant, :skeeper, :sname, :sopinion, :sreturntime, :ssituation, :stel, :susereason, :susetime
  validates :sname, :presence => true
  validates :sapplicant, :presence => true
  validates :stel, :presence => true
  validates :susetime, :presence => true
  validates :susereason, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/video.rb
class Video < ActiveRecord::Base
   attr_accessible :name,:avatar

  mount_uploader :avatar, EpictureUploader
  
end

app/controllers/equipment_controller.rb
#encoding:utf-8
class EquipmentController < ApplicationController

  def index
    @equipment=Equipment.page(params[:page]).per(3)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @equipment }
    end
  end

  def list
    @lists=Equipment.page(params[:page]).per(4)
  end

  def show
    @equipment = Equipment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @equipment }
    end
  end

  def new
    @equipment = Equipment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @equipment }
    end
  end

  def edit
    @equipment = Equipment.find(params[:id])
  end

  
  def create
    @equipment = Equipment.new(params[:equipment])

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: '成功创建设备.' }
        format.json { render json: @equipment, status: :created, location: @equipment }
      else
        format.html { render action: "new" }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @equipment = Equipment.find(params[:id])

    respond_to do |format|
      if @equipment.update_attributes(params[:equipment])
        format.html { redirect_to @equipment, notice: '成功更新设备.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @equipment = Equipment.find(params[:id])
    @equipment.destroy

    respond_to do |format|
      format.html { redirect_to equipment_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/eorders_helper.rb
module EordersHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/sorders_helper.rb
module SordersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/vedios_helper.rb
module VediosHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/equipment/_equipment.html.erb
<tr>
    <td class="span2">
    <%= image_tag(equipment.epicture.url(:one)) if equipment.epicture.present? %>
    </td>
    <td class="span3">
        设备名称：<%= equipment.ename %>
        <br />   
        设备类型：<%= equipment.etype %>
        <br /> 
        设备清单：<%= equipment.elist %>
        <br /> 
        设备报价：<%= equipment.eprice %>￥
        <br /> 
        设备剩余量：<%= equipment.eremain %>
        <br /> 
    </td>
    <td class="span2">
        <br />
    <%= link_to '预约',new_eorder_path(:equipment_id => equipment.id),:class => 'btn'%>
   </td>
</tr>

    

app/views/equipment/_form.html.erb
<%= form_for(@equipment, :html => {:multipart => true}) do |f| %>
  <% if @equipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@equipment.errors.count, "error") %> prohibited this equipment from being saved:</h2>

      <ul>
      <% @equipment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
        <label>设备图片</label>
        <%= f.file_field :epicture %>
       
  </div>
  <div class="field">
    <%= f.label :设备名 %><br />
    <%= f.text_field :ename %>
  </div>
  <div class="field">
    <%= f.label :设备型号 %><br />
    <%= f.text_field :etype %>
  </div>
  <div class="field">
    <%= f.label :设备清单 %><br />
    <%= f.text_area :elist %>
  </div>
  <div class="field">
    <%= f.label :设备价格 %><br />
    <%= f.number_field :eprice %>
  </div>
  <div class="field">
    <%= f.label :设备剩余量 %><br />
    <%= f.number_field :eremain %>
  </div>
  <div class="btn">
    <%= f.submit '提交' %>
  </div>
<% end %>

app/views/equipment/edit.html.erb
<h1>编辑设备</h1>

<%= render 'form' %>

<%= link_to '显示', @equipment %> |
<%= link_to '返回', equipment_index_path %>

app/views/equipment/index.html.erb
<div class="container2">
  <div class="center_content">
    <div class="left_nav">
      <ul>
          <li><%= link_to '实验设备',equipment_index_path%></a></li>
            <li><%= link_to '预约情况',eorders_path%></a></li>
            <li><a href="#">使用情况</a></li>
        </ul>
  </div>

<div class="right_content">
      <div class="logoer"><%= image_tag 'equipment_02.gif'%></div>
          <div class="post">
            <table class="table">
              <%= render @equipment %>
            </table>   
          </div>
          <hr >
    </div>
</div>
<div class="centerplay">
    <%= paginate @equipment %>
</div> 
<br />
</div>

app/views/equipment/list.html.erb
<div class="container2">
  <div class="center_content">
    <div class="left_nav">
      <ul>
        </ul>
  </div>

<div class="right_content">
      <div class="logoer"><%= image_tag 'equipment_02.gif'%></div>
          <div class="post">
            <table class="table">
              <tr>
                <th>设备名称</th>
                <th>类型</th>
                <th>设备清单</th>
                <th>报价</th>
                <th>剩余</th>                
              </tr>
              <% @lists.each do |list|%>
              <tr>
                <td class="span2">
                <%= list.ename %> 
                </td>
                <td class="span1">  
                <%= list.etype %>
                </td>
                <td class="span3">
                <%= list.elist %>
                </td>
                <td class="span1">
                <%= list.eprice %>
                </td>
                <td class="span1">
                <%= list.eremain %>
                </td>
                <td>
                  <a href='#'><span class="label label-info">说明书下载</span></a>                    
                </td>
              </tr>
              <% end %>

            </table>
            <hr />
          </div>
    </div>
</div>
<div class="centerplay">
    <%= paginate @lists %>
</div> 

app/views/equipment/new.html.erb
<h1 align=center>新建设备</h1>
<div align=center>
<%= render 'form' %>

<%= link_to '返回', equipment_index_path %>
</div>

app/views/equipment/show.html.erb
<p id="notice"><%= notice %></p>
<p><%= image_tag(@equipment.epicture.url) if @equipment.epicture.present? %></p>
<p>
  <b>设备名:</b>
  <%= @equipment.ename %>
</p>

<p>
  <b>设备型号:</b>
  <%= @equipment.etype %>
</p>

<p>
  <b>设备清单:</b>
  <%= @equipment.elist %>
</p>

<p>
  <b>设备价格:</b>
  <%= @equipment.eprice %>
</p>

<p>
  <b>设备剩余量:</b>
  <%= @equipment.eremain %>
</p>


<%= link_to '编辑', edit_equipment_path(@equipment) %> |
<%= link_to '返回', equipment_index_path %>