config/routes.rb
Swpuart::Application.routes.draw do

  resources :rules

  resources :sorders
  resources :line_items
  resources :carts
  resources :eorders
  resources :videos

  mount Ckeditor::Engine => '/ckeditor'

  mount Rich::Engine => '/rich', :as => 'rich'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => 'static_pages#home'
  resources :sites do
    collection do
    get 'siteorder'
    end
  end

  resources :equipment do
    collection do
      get 'list'
    end
  end

  resources :notices

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :line_items,:dependent => :destroy
end

app/models/eorder.rb
class Eorder < ActiveRecord::Base
  attr_accessible :ename,:eapplicant, :eartopinion, :ekeeper, :ereturntime, :esituation, :etel, :eusereason, :eusetime,:equipment_id
  validates :ename, :presence => true
  validates :eapplicant, :presence => true
  validates :etel, :presence => true
  validates :eusetime, :presence => true
  validates :eusereason, :presence => true

  #has_many :line_items
  #before_destroy :ensure_not_referenced_by_any_line_item

  belongs_to :equipment


  private
  def ensure_not_referenced_by_any_line_item
  	if line_items.empty?
  		return true
  	else
  		errors.add(:base,'11111')
  		return false
  	end
  end
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  attr_accessible :elist, :ename, :eprice, :eremain, :etype,:epicture,:epicture_cache,:remove_epicture
 


  mount_uploader :epicture, AvatarUploader

  # has_many :eorders, :dependent => :destroy

  validates :ename, :presence => true
  validates :eremain, :presence => true




end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :eorder_id
  belongs_to :eorder
  belongs_to :cart
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  attr_accessible :ncontent, :nfilenumber, :ntitle
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  attr_accessible :rcontent, :rpublisher, :rtitle
end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :sdescribe, :sname, :sstate,:spicture
  mount_uploader :spicture, SpictureUploader
end

app/models/sorder.rb
class Sorder < ActiveRecord::Base
  attr_accessible :sapplicant, :skeeper, :sname, :sopinion, :sreturntime, :ssituation, :stel, :susereason, :susetime
  validates :sname, :presence => true
  validates :sapplicant, :presence => true
  validates :stel, :presence => true
  validates :susetime, :presence => true
  validates :susereason, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/video.rb
class Video < ActiveRecord::Base
   attr_accessible :name,:avatar

  mount_uploader :avatar, EpictureUploader
  
end

app/controllers/line_items_controller.rb
#encoding:utf-8
class LineItemsController < ApplicationController
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart=current_cart
    eorder=Eorder.find(params[:eorder_id])
    @line_item=@cart.line_items.build
    @line_item.eorder=eorder
    # @line_item = LineItem.new(params[:line_item])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart, notice: 'Line item was successfully created.' }
        format.json { render json: @line_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/eorders_helper.rb
module EordersHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/sorders_helper.rb
module SordersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/vedios_helper.rb
module VediosHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :eorder_id %><br />
    <%= f.number_field :eorder_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit '提交' %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th>Eorder</th>
    <th>Cart</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.eorder_id %></td>
    <td><%= line_item.cart_id %></td>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Eorder:</b>
  <%= @line_item.eorder_id %>
</p>

<p>
  <b>Cart:</b>
  <%= @line_item.cart_id %>
</p>


<%= link_to '编辑', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>