config/routes.rb
Swpuart::Application.routes.draw do

  resources :rules

  resources :sorders
  resources :line_items
  resources :carts
  resources :eorders
  resources :videos

  mount Ckeditor::Engine => '/ckeditor'

  mount Rich::Engine => '/rich', :as => 'rich'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => 'static_pages#home'
  resources :sites do
    collection do
    get 'siteorder'
    end
  end

  resources :equipment do
    collection do
      get 'list'
    end
  end

  resources :notices

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :line_items,:dependent => :destroy
end

app/models/eorder.rb
class Eorder < ActiveRecord::Base
  attr_accessible :ename,:eapplicant, :eartopinion, :ekeeper, :ereturntime, :esituation, :etel, :eusereason, :eusetime,:equipment_id
  validates :ename, :presence => true
  validates :eapplicant, :presence => true
  validates :etel, :presence => true
  validates :eusetime, :presence => true
  validates :eusereason, :presence => true

  #has_many :line_items
  #before_destroy :ensure_not_referenced_by_any_line_item

  belongs_to :equipment


  private
  def ensure_not_referenced_by_any_line_item
  	if line_items.empty?
  		return true
  	else
  		errors.add(:base,'11111')
  		return false
  	end
  end
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  attr_accessible :elist, :ename, :eprice, :eremain, :etype,:epicture,:epicture_cache,:remove_epicture
 


  mount_uploader :epicture, AvatarUploader

  # has_many :eorders, :dependent => :destroy

  validates :ename, :presence => true
  validates :eremain, :presence => true




end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :eorder_id
  belongs_to :eorder
  belongs_to :cart
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  attr_accessible :ncontent, :nfilenumber, :ntitle
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  attr_accessible :rcontent, :rpublisher, :rtitle
end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :sdescribe, :sname, :sstate,:spicture
  mount_uploader :spicture, SpictureUploader
end

app/models/sorder.rb
class Sorder < ActiveRecord::Base
  attr_accessible :sapplicant, :skeeper, :sname, :sopinion, :sreturntime, :ssituation, :stel, :susereason, :susetime
  validates :sname, :presence => true
  validates :sapplicant, :presence => true
  validates :stel, :presence => true
  validates :susetime, :presence => true
  validates :susereason, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/video.rb
class Video < ActiveRecord::Base
   attr_accessible :name,:avatar

  mount_uploader :avatar, EpictureUploader
  
end

app/controllers/sites_controller.rb
#encoding:utf-8
class SitesController < ApplicationController

  def index
     #@sites = Site.all
    # @sites = Kaminari.paginate_array(sites).page(params[:page]).per(10)
    @sites=Site.page(params[:page]).per(8)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sites }
    end
  end

  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site }
    end
  end


  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site }
    end
  end

  def edit
    @site = Site.find(params[:id])
  end

  def create
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: '成功创建场地.' }
        format.json { render json: @site, status: :created, location: @site }
      else
        format.html { render action: "new" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to @site, notice: '成功更新场地.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  def siteorder
    #@orders=Site.find_all_by_sstate("忙碌")
    #@orders=Site.find_by_sql("select * from sites where sstate='忙碌'")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/eorders_helper.rb
module EordersHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/sorders_helper.rb
module SordersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/vedios_helper.rb
module VediosHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
        <label>场地图片</label>
        <%= f.file_field :spicture %>
       
  </div>
  <div class="field">
    <%= f.label :场地名 %><br />
    <%= f.text_field :sname %>
  </div>
  <div class="field">
    <%= f.label :场地描述 %><br />
    <%= f.text_area :sdescribe %>
  </div>
  <div class="field">
    <%= f.label :场地状态 %><br />
    <%= f.text_field :sstate %>
  </div>
  <div class="actions">
    <%= f.submit '提交' %>
  </div>
<% end %>

app/views/sites/_site.html.erb
<tr>
	<td class="span2">
		<%= image_tag(site.spicture.url(:one)) if site.spicture.present? %>  
	</td>
	<td class="span3">
    <%= link_to site.sname ,site%><br />
    <%= site.sdescribe %><br />
    <%= site.sstate %><br />
    </td>
    <td class="span2">
    	<br />
    	<%= link_to '预约', new_sorder_path,:class => 'btn' %>  
    </td>  
 </tr>
      


  

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to '显示', @site %> |
<%= link_to '返回', sites_path %>

app/views/sites/index.html.erb
<div class="container2">
<div class="center_content">
  <div class="left_nav">
      <ul>
          <li><%= link_to '场地设施',sites_path%></li>
            <li><%= link_to '预约情况',sorders_path%></li>
            <li><a href="#">场地要求</a></li>
        </ul>
  </div>

<div class="right_content">
      <div class="logoer"><%= image_tag 'order_2.gif'%></div>
      <!--<ul id="place">
        <%= render @sites%> 
      </ul>-->
      <div class="post">
        <table class="table">
          <%= render @sites%>
        </table>   
      </div>
      <hr >
</div>
      
</div>
<div class="centerplay">
        <%= paginate @sites %>
      </div>  
<br />

</div>

app/views/sites/new.html.erb
<h1 align=center>新建场地</h1>
<div align=center>
<%= render 'form' %>

<%= link_to '返回', sites_path %>
</div>

app/views/sites/show.html.erb
<div class="container">
	<%= render :partial => @site%>
    <%= simple_format @site.sdescribe %>
<%= link_to '编辑', edit_site_path(@site) %> |
<%= link_to '返回', sites_path %>
</div>

app/views/sites/siteorder.html.erb
<% @orders.each do |list|%>
<%= link_to list.sname,list%>
<% end %>